{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.8.aar",
          "url": "lightweightcharts-3.8.8.aar",
          "size": 431856,
          "sha512": "2bb5d39733238447499ec7cea82facd0f44802ced0aed32e5dbfa7f78360a816db956ec6d22c8bbcc91da1ac0875501cb92f5390d0c4ac7fbffcdec9f282f8bf",
          "sha256": "cf5a963e16d7c6bf52d7854dd32bcb10c5811504853c870e9717958c98cfe977",
          "sha1": "3263ff77e60255ce282812eba1089ad260a6795b",
          "md5": "1f4922997309443204295074702b3fbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.8.aar",
          "url": "lightweightcharts-3.8.8.aar",
          "size": 431856,
          "sha512": "2bb5d39733238447499ec7cea82facd0f44802ced0aed32e5dbfa7f78360a816db956ec6d22c8bbcc91da1ac0875501cb92f5390d0c4ac7fbffcdec9f282f8bf",
          "sha256": "cf5a963e16d7c6bf52d7854dd32bcb10c5811504853c870e9717958c98cfe977",
          "sha1": "3263ff77e60255ce282812eba1089ad260a6795b",
          "md5": "1f4922997309443204295074702b3fbd"
        }
      ]
    }
  ]
}
