{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.4.aar",
          "url": "lightweightcharts-3.8.4.aar",
          "size": 431508,
          "sha512": "cce8d84d55efb9bebae3c8e0050461a8976c45f1b1e5beb08ddac439fa4ebc9b0ff70beda04ee56da7b46f9bddddbb353681abf7316ea246e4add4273cb68a5c",
          "sha256": "30843a298e801e2e58db92a3542b0909b09d539199ea7c8ced645d1087029a0e",
          "sha1": "743bc714bab5ed4dac56438e1c359af6325d2e84",
          "md5": "5eb7c8e755d292794c92157ff7030113"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.4.aar",
          "url": "lightweightcharts-3.8.4.aar",
          "size": 431508,
          "sha512": "cce8d84d55efb9bebae3c8e0050461a8976c45f1b1e5beb08ddac439fa4ebc9b0ff70beda04ee56da7b46f9bddddbb353681abf7316ea246e4add4273cb68a5c",
          "sha256": "30843a298e801e2e58db92a3542b0909b09d539199ea7c8ced645d1087029a0e",
          "sha1": "743bc714bab5ed4dac56438e1c359af6325d2e84",
          "md5": "5eb7c8e755d292794c92157ff7030113"
        }
      ]
    }
  ]
}
