{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.9.aar",
          "url": "lightweightcharts-3.8.9.aar",
          "size": 432322,
          "sha512": "9b1bf0403426e3de5af4db80f364c50f819ab42c7d60066f6116f0622874c40c81ca0c75beb0cc7fd4ae1599371e62525ce3c3ae8a8324eb048e6dff44a92dc4",
          "sha256": "c85cc23e2060725e80a95e43e7fa65fd57e3bffbb128a63c5da4bf42827bc561",
          "sha1": "fa92a5af8cfc452249b696de0405a0d313c62330",
          "md5": "43f2cfb91d8032578bffc536b8193918"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.9.aar",
          "url": "lightweightcharts-3.8.9.aar",
          "size": 432322,
          "sha512": "9b1bf0403426e3de5af4db80f364c50f819ab42c7d60066f6116f0622874c40c81ca0c75beb0cc7fd4ae1599371e62525ce3c3ae8a8324eb048e6dff44a92dc4",
          "sha256": "c85cc23e2060725e80a95e43e7fa65fd57e3bffbb128a63c5da4bf42827bc561",
          "sha1": "fa92a5af8cfc452249b696de0405a0d313c62330",
          "md5": "43f2cfb91d8032578bffc536b8193918"
        }
      ]
    }
  ]
}
