{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.3.aar",
          "url": "lightweightcharts-3.8.3.aar",
          "size": 431506,
          "sha512": "906774da3763962fefb53d75f7114bf3476aa53985f41c328037983a5fa1ab5a9fa15047f9bf04ad91cd224f61427fd431cea8dfc2fb4950c18634ccc7a34a97",
          "sha256": "60ad2b92393e59b8afbc9eb33a1ca5ac6f4a7ca9e730be016e409f844ca9b5fa",
          "sha1": "a407b3f089544b25e192e9b4eb2adff8d9704887",
          "md5": "d56445ce4cb128bdd1d11ba6249c82db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.3.aar",
          "url": "lightweightcharts-3.8.3.aar",
          "size": 431506,
          "sha512": "906774da3763962fefb53d75f7114bf3476aa53985f41c328037983a5fa1ab5a9fa15047f9bf04ad91cd224f61427fd431cea8dfc2fb4950c18634ccc7a34a97",
          "sha256": "60ad2b92393e59b8afbc9eb33a1ca5ac6f4a7ca9e730be016e409f844ca9b5fa",
          "sha1": "a407b3f089544b25e192e9b4eb2adff8d9704887",
          "md5": "d56445ce4cb128bdd1d11ba6249c82db"
        }
      ]
    }
  ]
}
