{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.5.aar",
          "url": "lightweightcharts-3.8.5.aar",
          "size": 431506,
          "sha512": "3445f9621d568c8bc4cbf1ad48bc051b2f8560eda7901a6d2f7def1ee254c449107183e0ead1b6ee00d4b8fada29f77062cce631c7ac80502a29259897df4c29",
          "sha256": "5e9520e579b9532744c99c95eb5179c102bc9becdeadd3acc9e297348d5efeab",
          "sha1": "6c40147df4786ba950804878656b76a7d0f05c29",
          "md5": "e84f464517e9cc74d03e64eb00c8d1f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.5.aar",
          "url": "lightweightcharts-3.8.5.aar",
          "size": 431506,
          "sha512": "3445f9621d568c8bc4cbf1ad48bc051b2f8560eda7901a6d2f7def1ee254c449107183e0ead1b6ee00d4b8fada29f77062cce631c7ac80502a29259897df4c29",
          "sha256": "5e9520e579b9532744c99c95eb5179c102bc9becdeadd3acc9e297348d5efeab",
          "sha1": "6c40147df4786ba950804878656b76a7d0f05c29",
          "md5": "e84f464517e9cc74d03e64eb00c8d1f9"
        }
      ]
    }
  ]
}
