{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.7.aar",
          "url": "lightweightcharts-3.8.7.aar",
          "size": 431810,
          "sha512": "dd98b5f3e1e43a41f1c499a2587dc2f5a4f9126c44f21e531df5b22c2b4287d69c462bd5ff0a53727dc44f92ddcee15fe5fdabc881ee8f9715cddf8ff70d79e0",
          "sha256": "e08e4efa3e22670e84b82c94706cd10f13c102d96f526df1a8549cafe284ff70",
          "sha1": "f81451068108c8e5c318aca6222d6ce758148b17",
          "md5": "9150055f7900405bd95dba10e836c29f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.7.aar",
          "url": "lightweightcharts-3.8.7.aar",
          "size": 431810,
          "sha512": "dd98b5f3e1e43a41f1c499a2587dc2f5a4f9126c44f21e531df5b22c2b4287d69c462bd5ff0a53727dc44f92ddcee15fe5fdabc881ee8f9715cddf8ff70d79e0",
          "sha256": "e08e4efa3e22670e84b82c94706cd10f13c102d96f526df1a8549cafe284ff70",
          "sha1": "f81451068108c8e5c318aca6222d6ce758148b17",
          "md5": "9150055f7900405bd95dba10e836c29f"
        }
      ]
    }
  ]
}
