{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tradingview",
    "module": "lightweightcharts",
    "version": "3.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lightweightcharts-3.8.6.aar",
          "url": "lightweightcharts-3.8.6.aar",
          "size": 431814,
          "sha512": "5df170df624fa5133dde57e5bb979e991e8ebf2326c35e91df46fabcbd9c207ce339a9c097781dc9ea6dd8e073756fc7a033ecb509a78baac1a2801ac4312112",
          "sha256": "b924457a90abf7c108fd9aa754b7d10410a41466428ffcc7320fb8d1af73b04b",
          "sha1": "3dbd3496e6ab80ff5c19d90b1cf18acdb31cd584",
          "md5": "0bbb5a6c69e1a87e6aceb9a1a1f682ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "lightweightcharts-3.8.6.aar",
          "url": "lightweightcharts-3.8.6.aar",
          "size": 431814,
          "sha512": "5df170df624fa5133dde57e5bb979e991e8ebf2326c35e91df46fabcbd9c207ce339a9c097781dc9ea6dd8e073756fc7a033ecb509a78baac1a2801ac4312112",
          "sha256": "b924457a90abf7c108fd9aa754b7d10410a41466428ffcc7320fb8d1af73b04b",
          "sha1": "3dbd3496e6ab80ff5c19d90b1cf18acdb31cd584",
          "md5": "0bbb5a6c69e1a87e6aceb9a1a1f682ca"
        }
      ]
    }
  ]
}
